config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/calendar", to: 'pages#calendar'
  get "/my_profile", to: 'pages#my_profile'
  get "/analysis", to: 'pages#analysis'
  get '/notifications', to: 'pages#notifications'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subscriptions do
    patch 'update_notification', to: 'subscriptions#update_notification'
      member do
        patch 'add_parasite', as: 'add_parasite'
        delete 'delete_parasite', as: 'delete_parasite'
      end
  end
  resources :parasites, only: [ :new, :create, :delete, :destroy, :index, :show]
  resources :payment_methods
end

app/models/parasite.rb
class Parasite < ApplicationRecord
  belongs_to :user
  has_many :subscription_parasites, dependent: :destroy
  has_many :subscriptions, through: :subscription_parasites
end

app/controllers/parasites_controller.rb
class ParasitesController < ApplicationController
def index
  @parasites = Parasite.all
end

def show
  @parasite = Parasite.find(params[:id])
end

  def new
    @parasite = Parasite.new
  end

  def create

    @parasite = Parasite.new(name: parasite_params[:name], parasite_email: parasite_params[:parasite_email], notify_parasite: parasite_params[:notify_parasite])
    @parasite.user = current_user
    if @parasite.save

     return  redirect_to(subscription_path(parasite_params[:subscription_id]), notice: 'Friend added' ) unless parasite_params[:subscription_id].blank?
      redirect_to my_profile_path
    else
      render :new
    end
  end

  def destroy
    @parasite = Parasite.find(params[:id])
    @parasite.destroy
    redirect_to my_profile_path
  end

  def parasite_params
    params.require(:parasite).permit(:name, :parasite_email, :notify_parasite, :subscription_id)
  end
end

app/views/parasites/_form.html.erb
<div class="container">
  <div class="row">
    <div class = " col-xs-12 col-md-6 offset-3">
      <%= simple_form_for(@parasite) do |f| %>
      <%= f.error_notification %>

      <div class = "form-group">
        <br>
        <br>
        <%= f.input :name, placeholder: 'Name of your lucky friend' %>
        <%= f.input :parasite_email, placeholder: 'friend@gmail.com' %>
        <%= f.input :notify_parasite %>
        <%= f.hidden_field :subscription_id, value: params[:subscription_id] %>
        <p> We will send friendly email to your friend at the billing date to inform him you paid his subscription & he/she owes you a beer </p>

        <div clas = "form-action">
          <%= f.button :submit, class: 'btn btn-primary' %>
        </div>
      </div>

      <% end %>
    </div>
  </div>

app/views/parasites/_index.html.erb
<div class="parasites-container container">
  <div class="row">
    <% parasites.each do |para| %>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 single-parasite">

        <div class="para-avatar">
          <p class="initial"><%=  para.name[0,1] %></p>
        </div>
        <div class="para-details">
          <p class="para-name"><%=  para.name %> </p>
          <p class="para-subsc"><%= para.subscriptions.map{ |sub| sub.name }.join(", ") %></p>
        </div>
        <div class="deletefriend">
          <%= link_to "/parasites/#{para.id}", data: { confirm: 'Are you sure?' }, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>

        </div>
      </div>

    <% end %>
  </div>
</div>


<div id="back" class="btn btn-primary">
    <%= link_to "Add a friend", new_parasite_path   %>
</div>

app/views/parasites/index.html.erb
<%= render "index", parasites: @parasites %>

app/views/parasites/new.html.erb
 <%= render 'parasites/form', parasites: @parasites %>

app/views/parasites/show.html.erb
show.html.erb