config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/calendar", to: 'pages#calendar'
  get "/my_profile", to: 'pages#my_profile'
  get "/analysis", to: 'pages#analysis'
  get '/notifications', to: 'pages#notifications'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subscriptions do
    patch 'update_notification', to: 'subscriptions#update_notification'
      member do
        patch 'add_parasite', as: 'add_parasite'
        delete 'delete_parasite', as: 'delete_parasite'
      end
  end
  resources :parasites, only: [ :new, :create, :delete, :destroy, :index, :show]
  resources :payment_methods
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <%= image_tag "logo.png"%>
    <p><i class="far fa-copyright"></i> 2018 Monetizeur, all rights reserved</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to subscriptions_path, class: "navbar-brand" do %>
    <%= image_tag "logo-small-white.png", id:"nav-logo" %>
    <div style="display: none;" id="other-img"> <%= image_path 'logosmall.png' %></div>
    <div style="display: none;" id="init-img"> <%= image_path 'logo-small-white.png' %></div>
  <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

  <% if user_signed_in? == false %>
    <ul class="navbar-nav mr-auto">
      <li class= "nav-item "><%= link_to "Log in", new_user_session_path, class: "nav-link"%> </li>
      <li class= "nav-item"><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %> </li>
    </ul>

  <% else %>

      <ul class="navbar-nav mr-auto">
        <div class="nav-link" id="notification">
        <% unless current_user.subscriptions_today.empty? %>
          <div class="notify-circle"></div>
        <% end %>
       <!--    <div id="notice_wrapper">
            <a You have no notifications today</p> -->
        <div class="dropdown nav-link">
          <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell"></i>
          </div>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if current_user.subscriptions_today.empty? %>
         <div class="notification-message"> <p>You have no notifications today</p></div>

        <% end %>

               <% current_user.subscriptions_today.each do |n| %>
                 <!-- design notif card here -->
                   <%= link_to subscription_path(n), class: "dropdown-item" do %>
                      <div class="notification-image">
                        <div class="notification-logo">
                        <% if n.name == "Amazon Prime" %>
                          <%= image_tag "amazon.png", alt: "amazon" %>
                        <% elsif n.name == "Apple Music" %>
                          <%= image_tag "apple.png", alt: "apple" %>
                        <% elsif n.name == "Dropbox" %>
                          <%= image_tag "dropbox.png", alt: "dropbox" %>
                        <% elsif n.name == "iCloud" %>
                          <%= image_tag "icloud.png", alt: "icloud" %>
                        <% elsif n.name == "LinkedIn" %>
                          <%= image_tag "linkedin.png", alt: "linkedin" %>
                        <% elsif n.name == "Netflix" %>
                          <%= image_tag "netflix.png", alt: "netflix" %>
                        <% elsif n.name == "Spotify" %>
                          <%= image_tag "spotify.png", alt: "spotify" %>
                        <% else %>
                          <%= image_tag "logosmall.png", alt: "logo" %>
                        <% end %>
                        </div>
                         <div class="notification-name">
                          <p class="notif-name"><%=  n.name %>:&nbsp;</p>
                         </div>
                         <div><p class="notif-cost"><%=  n.cost %> €</p></div>
                         <div><p class="notif-date"><%=  n.billing_date %></p></div>
                      </div>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>



        <li class="nav-item">
          <%= link_to "Calendar", calendar_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Analytics", analysis_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", my_profile_path, class: "dropdown-item" %>
            <%= link_to "My Subscriptions", subscriptions_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_main.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-main">
  <%= link_to subscriptions_path, class: "navbar-brand-main" do %>
    <%= image_tag "logosmall.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

  <% if user_signed_in? == false %>
    <ul class="navbar-nav mr-auto">
      <li class= "nav-item-main"><%= link_to "Log in", new_user_session_path, class: "nav-link"%> </li>
      <li class= "nav-item-main"><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %> </li>
    </ul>

  <% else %>


      <ul class="navbar-nav mr-auto">
        <div class="nav-link" id="notification">
        <% unless current_user.subscriptions_today.empty? %>
          <div class="notify-circle"></div>
        <% end %>
       <!--    <div id="notice_wrapper">
            <a You have no notifications today</p> -->
        <div class="dropdown nav-link">
          <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell"></i>
          </div>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if current_user.subscriptions_today.empty? %>
         <div class="notification-message"> <p>You have no notifications today</p></div>

        <% end %>

               <% current_user.subscriptions_today.each do |n| %>
                 <!-- design notif card here -->
                   <%= link_to subscription_path(n), class: "dropdown-item" do %>
                      <div class="notification-image">
                        <div class="notification-logo">
                        <% if n.name == "Amazon Prime" %>
                          <%= image_tag "amazon.png", alt: "amazon" %>
                        <% elsif n.name == "Apple Music" %>
                          <%= image_tag "apple.png", alt: "apple" %>
                        <% elsif n.name == "Dropbox" %>
                          <%= image_tag "dropbox.png", alt: "dropbox" %>
                        <% elsif n.name == "iCloud" %>
                          <%= image_tag "icloud.png", alt: "icloud" %>
                        <% elsif n.name == "LinkedIn" %>
                          <%= image_tag "linkedin.png", alt: "linkedin" %>
                        <% elsif n.name == "Netflix" %>
                          <%= image_tag "netflix.png", alt: "netflix" %>
                        <% elsif n.name == "Spotify" %>
                          <%= image_tag "spotify.png", alt: "spotify" %>
                        <% else %>
                          <%= image_tag "logosmall.png", alt: "logo" %>
                        <% end %>
                        </div>

                        <div style="width: 80px;">
                          <p class="notif-name"><%=  n.name %></p>
                         </div>
                         <div><p class="notif-cost"><%=  n.cost %> €</p></div>
                         <div><p class="notif-date"><%=  n.billing_date %></p></div>
                      </div>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>





        <li class="nav-item">
          <%= link_to "Calendar", calendar_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Analytics", analysis_path, class: "nav-link" %>
        </li>
        <li class="nav-item-main dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "My Profile", my_profile_path, class: "dropdown-item" %>
            <%= link_to "My Subscriptions", subscriptions_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</div>