config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/calendar", to: 'pages#calendar'
  get "/my_profile", to: 'pages#my_profile'
  get "/analysis", to: 'pages#analysis'
  get '/notifications', to: 'pages#notifications'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subscriptions do
    patch 'update_notification', to: 'subscriptions#update_notification'
      member do
        patch 'add_parasite', as: 'add_parasite'
        delete 'delete_parasite', as: 'delete_parasite'
      end
  end
  resources :parasites, only: [ :new, :create, :delete, :destroy, :index, :show]
  resources :payment_methods
end

app/views/pages/analysis.html.erb
<div class="analysis">

  <div class="analysis-profile">

    <div class="info-a">
      <div class="info-picture">
        <h5><i class="fas fa-wallet"></i>  Subscriptions <%= (Date.today).strftime("%B") %> <%= Date.today.year %></h5>
      </div>
      <div class="info-text">
        <p><%= current_user.total_monthly_cost %> €</p>
      </div>
    </div>

    <div class="info-a">
      <div class="info-picture">
        <h5><i class="fas fa-user-clock"></i>  Compared to <%= (Date.today - 1.year).strftime("%B") %> <%= Date.today.year - 1 %></h5>
      </div>
      <div class="info-text3">
        <% if  current_user.growth_subscription_to_month == 100 %>
          <p class="total-increase"><i class="fas fa-caret-up"></i> <%= current_user.growth_subscription_to_month%> % </p>
          <p class="notify-me"> <i class="fas fa-info-circle"></i> You didn't have any subscriptions last year, so we indicated a growth of 100% </class></p>
        <% elsif  current_user.growth_subscription_to_month > 0 %>
          <p class="total-increase"><i class="fas fa-caret-up"></i> <%= current_user.growth_subscription_to_month%> % </p>
        <% else %>
          <p class="total-decrease"><i class="fas fa-caret-down"></i> <%= current_user.growth_subscription_to_month%> % </p>
        <% end %>
      </div>
    </div>

    <div class="info-a">
      <h5><i class="fas fa-file-invoice-dollar"></i>  Year to date Spending </h5>
        <div class="ytd-all">
        <div class="info-text ytd-total">
          <h5 class="ytd-title main-title-ytd">TOTAL</h5>
          <p><%= current_user.ytd_spending %> €</p>
        </div>
        <div class="most-expensive">
          <h5 class="ytd-title main-title-ytd">MOST EXPENSIVE</h5>
          <div class="ytd-mostexpensive">
            <div class="ytd-subsc">
              <h5 class="ytd-title"><i class="fas fa-sort-amount-up"></i>&nbsp;SUBSCRIPTION</h5>
              <div class="info-text2">
              <% if current_user.most_expensive.nil? %>
                <p> No subscriptions yet </p>
              <% else %>
              <p> <%= current_user.most_expensive[1] %> € </p>
              <div class="image-app">
                <% if current_user.most_expensive[0] == "Amazon Prime" %>
                    <%= image_tag "amazon.png", alt: "amazon" %>
                  <% elsif current_user.most_expensive[0] == "Apple Music" %>
                    <%= image_tag "apple.png", alt: "apple" %>
                  <% elsif current_user.most_expensive[0] == "Dropbox" %>
                    <%= image_tag "dropbox.png", alt: "dropbox" %>
                  <% elsif current_user.most_expensive[0] == "iCloud" %>
                    <%= image_tag "icloud.png", alt: "icloud" %>
                  <% elsif current_user.most_expensive[0] == "LinkedIn" %>
                    <%= image_tag "linkedin.png", alt: "linkedin" %>
                  <% elsif current_user.most_expensive[0] == "Netflix" %>
                    <%= image_tag "netflix.png", alt: "netflix" %>
                  <% elsif current_user.most_expensive[0] == "Spotify" %>
                    <%= image_tag "spotify.png", alt: "spotify" %>
                  <% else %>
                    <%= image_tag "logosmall.png", alt: "logo" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
            <div class="ytd-category">
              <h5 class="ytd-title"><i class="fas fa-chart-pie">&nbsp;</i>CATEGORY</h5>
              <div class="info-text">
                <% if current_user.most_expensive_category  .nil? %>
                <p> No subscriptions </p>
                <% else %>
                <p> <%= current_user.most_expensive_category[1] %> €
                  <% if current_user.most_expensive_category[0] == "Media" %>
                    Media color:red
                  <% elsif current_user.most_expensive_category[0] == "Wellbeing" %>
                    <p style="color:#5CB566;">Wellbeing</p>
                  <% elsif current_user.most_expensive_category[0] == "Streaming" %>
                    <p style="color:lightblue;">Streaming</p>
                  <% elsif current_user.most_expensive_category[0] == "Leisure" %>
                    <p style="color:darkblue;">Leisure</p>
                  <% elsif current_user.most_expensive_category[0] == "Social" %>
                    <p style="color:orange;">Social</p>
                  <% elsif current_user.most_expensive_category[0] == "Shopping" %>
                    <p style="color:pink;">Leisure</p>
                  <% elsif current_user.most_expensive_category[0] == "Food" %>
                    <p style="color:darkblue;">Food</p>
                  <% elsif current_user.most_expensive_category[0] == "Technology" %>
                    <p style="color:gray;">Technology</p>
                  <% elsif current_user.most_expensive_category[0] == "Other" %>
                    <p style="color:purple;">Other</p>
                  <% end %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>


    <div class="info-a">
      <div class="info-picture">
        <h5><i class="far fa-kiss-wink-heart"></i> Friend using the most app's </h5>
      </div>
      <div class="info-text4">
        <% if current_user.parasites.blank?%>
          <p> No one is using your app's</p>
        <% else %>
          <p> <%= current_user.parasites_count[0] %> uses <%= current_user.parasites_count[1] %> subscriptions: </p>
          <div class="picture-app-all">
            <% current_user.parasite_app_name.each do |app| %>
            <% if app == "Amazon Prime" %>
                <%= image_tag "amazon.png", alt: "amazon" %>
              <% elsif app == "Apple Music" %>
                <%= image_tag "apple.png", alt: "apple" %>
              <% elsif app == "Dropbox" %>
                <%= image_tag "dropbox.png", alt: "dropbox" %>
              <% elsif app == "iCloud" %>
                <%= image_tag "icloud.png", alt: "icloud" %>
              <% elsif app == "LinkedIn" %>
                <%= image_tag "linkedin.png", alt: "linkedin" %>
              <% elsif app == "Netflix" %>
                <%= image_tag "netflix.png", alt: "netflix" %>
              <% elsif app == "Spotify" %>
                <%= image_tag "spotify.png", alt: "spotify" %>
              <% else %>
                <%= image_tag "logosmall.png", alt: "logo" %>
              <% end %>
            <% end %>
          <% end %>
        </div>

      </div>
    </div>

        <div class="info-a">
      <div class="info-picture">
        <h5><i class="far fa-handshake"></i> Free trials</h5>
      </div>
      <div class="info-text">
        <% current_user.subscriptions.each do |test| %>
          <% if test.trial? %>
          <p><%= test.name %>&nbsp;&nbsp;</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

<div class="spending-container">
<h3> My spending Dashboard </h3>

  <div class="cards-analysis">


      <div class="chartkick first">
        <h4> Monthly subscription cost for the next 12 months</h4>
        <%= column_chart @chart_array, legend: false,  colors: ["#748CAB"], height: "300px", xtitle: "months", ytitle: "cost in €" %>
      </div>
      <div class="chartkick second">
        <h4> Yearly subscription cost for the last 5 years</h4>
        <%= line_chart @line_array, legend: false,  colors: ["#748CAB"], height: "300px", xtitle: "years", ytitle: "cost in €" %>
      </div>
      <div class="chartkick third">
         <h4> This month's subscription cost per category </h4>
        <%= pie_chart @pie_chart_data_this_month, colors: @colors_month, heigth: "250px" %>
      </div>
      <div class="chartkick forth">
        <h4> This year's subscription cost per category </h4>
        <%= pie_chart @pie_chart_data_this_year, colors: @colors_year, heigth: "250px"  %>
      </div>

      <div class="chartkick fifth">
        <h4> Yearly spending per subscription </h4>
          <%= pie_chart @pie_chart_data_per_app, heigth: "250px"%>
          <p> Yearly spending in € per subscription </p>
      </div>
      <div class="chartkick sixth">
              <h4> How nice am I? </h4>
          <%= pie_chart current_user.how_nice_am_i, heigth: "250px"%>
          <p> Total cost in € of subscription used by friends </p>
      </div>
  </div>
  </div>


</div>

app/views/pages/calendar.html.erb
<div class="wrapper-calendar">
  <div class="row">
    <div class = "col-xs-1 col-md-2 arrow-wrap">
      <div id="previous-month" class="btn btn-primary"><i class="fas fa-chevron-left"></i></div>
    </div>

    <div class = "col-xs-10 col-md-8" id="wrapping-calendar">
      <div id='calendar' data-subscriptions="<%= @one_year_events %>"></div>
    </div>

    <div class = "col-xs-1 col-md-2 arrow-wrap">
      <div id="next-month" class="btn btn-primary"><i class="fas fa-chevron-right"></i></div>
    </div>
  </div>

  <div class="button-wrapper">
    <br>
    <div id="back" class="btn btn-primary index">
      <%= link_to "Add a subscription", new_subscription_path   %>
    </div>
  </div>

</div>
<br>
<br>
<br>

app/views/pages/home.html.erb
<div class="banner">
<br>
<br>
<br>
  <div class="container">
    <p>MONETIZEUR<p>
    <h1>Enjoy full <span class="transparent">transparency</span> of your subscriptions</h1>
  </div>
</div>

<br>
<br>
<br>

<div class="product-features container">
  <div class="all-features">
      <div class="single-feature first">
        <%= image_tag "feature-easy-subsc.png", height: 300, width: 400 %>
        <h4 class="feature-title">EASY</h4>
        <p class="feature-info">Easily add and record your subscriptions</p>
      </div>
      <div class="single-feature second">
        <%= image_tag "feature-subsc-glance.png", height: 300, width: 400 %>
        <h4 class="feature-title">AT A GLANCE</h4>
        <p class="feature-info">Access overviews that automatically calculate your spending and get an streamlined analysis</p>
      </div>
      <div class="single-feature third">
        <%= image_tag "feature-get-notified.png", height: 300, width: 400 %>
        <h4 class="feature-title">NOTIFICATIFICATIONS</h4>
        <p class="feature-info">Always know when your next bill is coming with smart Monetizeur notifications</p>
      </div>
      <div class="single-feature last">
        <%= image_tag "feature-track-others.png", height: 300, width: 400 %>
        <h4 class="feature-title">TRACKING</h4>
        <p class="feature-info">See who is benefiting from your subscriptions and remind them they owe you a little present</p>
      </div>
  </div>
</div>
<div class="reviews">
  <p class="upcase">DON'T JUST TAKE IT FROM US</p>
  <p class="reviews-title">People <i class="fas fa-heart"></i> Monetizeur</p>
  <div class="reviews-all">
    <div class="review-single">
      <p class="reviews-content">"Very cool..used Monetizeur and found several subscriptions I did not know I was paying for. Now cancelled. Yes! #savingmoney"</p>
      <div class= "reviewer">
        <div class="reviewer-avatar">
          <%= image_tag "avatar1.jpg", height: 300, width: 400 %>
        </div>
        <div class="reviewer-name">
          <p>Nerea Pascual</p>
          <p id="website">@npdiaz</p>
        </div>
      </div>
    </div>

    <div class="review-single">
      <p class="reviews-content">"Monetizeur is awesome, saved me hundreds of dollars by finding an old blog host subscription I had forgotten about. I highly recommend it."</p>
      <div class= "reviewer">
        <div class="reviewer-avatar">
          <%= image_tag "avatar2.jpg", height: 300, width: 400 %>
        </div>
        <div class="reviewer-name">
          <p>Marie Loge</p>
          <p id="website">@marie.l</p>
        </div>
      </div>
    </div>

    <div class="review-single">
      <p class="reviews-content">"Monetizeur just cancelled a subscription for me that's been plaguing me for months. These guys kick ass (SaaS?). Check them out."</p>
      <div class= "reviewer">
        <div class="reviewer-avatar">
          <%= image_tag "avatar3.jpg", height: 300, width: 400 %>
        </div>
        <div class="reviewer-name">
          <p>Agnese Bockane</p>
          <p id="website">@agneseb</p>
        </div>
      </div>
    </div>

  </div>
</div>

<br>
<br>
<br>

app/views/pages/my_profile.html.erb
<div class="my-profile" >


  <div class="user-profile">
    <div class="profile-picture">
      <%= image_tag "avatar.jpg", class: "profile-picture-round"%>
    </div>
    <div class="profile info">

      <p class="profile-name"> <%= current_user.first_name %> <%= current_user.last_name %></p>
      <p class="profile-mail"> <%=current_user.email  %> </p>
      <div id="back" class="btn btn-primary">
        <%= link_to "Update your profile", edit_user_registration_path  %>
      </div>

    </div>
  </div>


  <div class="cards">

    <div class="summary">
      <h3>Summary</h3>
      <div class="summary-container">
        <div class="box subscriptions">
          <h5><i class="fas fa-wallet"></i>  Subscriptions <%= (Date.today).strftime("%B") %> <%= Date.today.year %></h5>
          <div class="subsc-cost">
            <p class="total-spent"> <%= current_user.total_monthly_cost %> € this month</p>
            <% if  current_user.growth_subscription > 0 %>
              <p class="total-increase"><i class="fas fa-caret-up"></i> <%= current_user.growth_subscription%> % </p>
            <% else %>
              <p class="total-decrease"><i class="fas fa-caret-down"></i> <%= current_user.growth_subscription%> % </p>
            <% end %>
          </div>
          <div>
            <p class="next-subsc-cost"> <%= current_user.total_monthly_cost_next_month %> € next month</p>
          </div>
          <div class="info-btn-container">
            <%= link_to analysis_path do %>
            <div class="btn btn-primary" id="more-info">
              <i class="fas fa-sort-down"></i> MORE INFO
            </div>
            <% end %>
          </div>
        </div>

        <div class="box calendar-view">
          <%= link_to calendar_path do %>
          <h5><i class="far fa-calendar-alt"></i> Calendar <%= (Date.today).strftime("%B") %> <%= Date.today.year %></h5>
          <% end %>
          <div id='calendar' class='profile-calendar' data-subscriptions="<%= @one_year_events %>"></div>
        </div>
      </div>

    </div>

    <div class="Parasites-my-profile">
      <h3> Your "lovely" friends using your subscriptions </h3>
      <%= render "parasites/index", parasites: current_user.parasites %>
    </div>

    <div class="your-cards">
      <h3>Your cards</h3>
      <div class="cards-container container">
        <div class="row">
          <% @payment_methods.each do |pm|%>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 entire-card">
            <div class="single-card">
              <%= link_to payment_method_path(pm) do %>
                <% if pm.photo? %>
                  <%= cl_image_tag pm.photo, height: 300, width: 400 %>
                <% elsif pm.category == "Visa"%>
                  <%= image_tag "visa.jpg", height: 300, width: 400 %>
                <% elsif pm.category == "Amex"%>
                  <%= image_tag "amex.png", height: 300, width: 400 %>
                <% elsif pm.category == "Paypal"%>
                  <%= image_tag "paypal.png", height: 300, width: 400 %>
                <% elsif pm.category == "Mastercard"%>
                  <%= image_tag "master.jpg", height: 300, width: 400 %>
                <% end %>
              <% end %>
              <p class="pm-nickname"><%= link_to pm.card_nickname, payment_method_path(pm)%></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="btn-contain">
        <div id="back" class="btn btn-primary">
          <%= link_to "Add a card", new_payment_method_path   %>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/pages/notifications.html.erb
<% @subscriptions.each do |sub| %>
  <%= sub.name %>
<% end %>