config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/calendar", to: 'pages#calendar'
  get "/my_profile", to: 'pages#my_profile'
  get "/analysis", to: 'pages#analysis'
  get '/notifications', to: 'pages#notifications'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subscriptions do
    patch 'update_notification', to: 'subscriptions#update_notification'
      member do
        patch 'add_parasite', as: 'add_parasite'
        delete 'delete_parasite', as: 'delete_parasite'
      end
  end
  resources :parasites, only: [ :new, :create, :delete, :destroy, :index, :show]
  resources :payment_methods
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :payment_method
  belongs_to :user
  has_many :subscription_parasites, dependent: :nullify
  has_many :parasites, through: :subscription_parasites, dependent: :nullify


  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :subscription_type, presence: true
  validates :cost, presence: true
  validates :billing_date, presence: true

  before_validation :set_create_date

  def set_create_date
    if self.creation_date.nil?
      self.creation_date = Date.today
    end
  end

  def lifelong_cost(from_date, to_date)
    total_cost = 0
    if self.subscription_type == "Monthly"
      return calc_monthly(from_date, to_date).round(2)
    elsif self.subscription_type == "Quarterly"
      return calc_quartertly(from_date, to_date).round(2)
    elsif self.subscription_type == "Biannually"
      return calc_biannualy(from_date, to_date).round(2)
    else self.subscription_type == "Annually"
      return calc_yearly( from_date, to_date).round(2)
    end
  end

  def calc_monthly(from_date, to_date)
      cost = 0

      if self.trial? == true
        date_pay = self.billing_date
      else
        date_pay = from_date.nil? ? self.creation_date : from_date
      end

      if date_pay < self.creation_date
        date_pay = self.creation_date
      end
      to_date = to_date.nil? ? Date.today : to_date

      while date_pay < to_date
          cost += self.cost
          date_pay = date_pay + 1.months
      end
      return cost
  end

  def calc_quartertly(from_date, to_date)
        cost = 0

        if self.trial? == true
          date_pay = self.billing_date
        else
          date_pay = from_date.nil? ? self.creation_date : from_date
        end

        if date_pay < self.creation_date
        date_pay = self.creation_date
        end
      to_date = to_date.nil? ? Date.today : to_date

      while date_pay < to_date
          cost += self.cost
          date_pay = date_pay + 3.months
      end
      return cost
  end

    def calc_biannualy(from_date, to_date)
      cost = 0

        if self.trial? == true
          date_pay = self.billing_date
        else
          date_pay = from_date.nil? ? self.creation_date : from_date
        end

        if date_pay < self.creation_date
        date_pay = self.creation_date
        end
      to_date = to_date.nil? ? Date.today : to_date

      while date_pay < to_date
          cost += self.cost
          date_pay = date_pay + 6.months
      end
      return cost
  end

  def calc_yearly(from_date, to_date)
    cost = 0

    if self.trial? == true
      date_pay = self.billing_date
    else
      date_pay = from_date.nil? ? self.creation_date : from_date
    end

    if date_pay < self.creation_date
        date_pay = self.creation_date
        end
      to_date = to_date.nil? ? Date.today : to_date


      while date_pay < to_date
          cost += self.cost
          date_pay = date_pay + 12.months
      end
    return cost
  end

  def notify_today?
    notify = false
    return false if notification_date.nil? || !renewal_notification
    value_date = notification_date

    until value_date >= Date.today
        if self.subscription_type == "Monthly"
          value_date = value_date + 1.month
        elsif self.subscription_type == "Quarterly"
           value_date = value_date + 3.months
        elsif self.subscription_type == "Biannually"
           value_date = value_date + 6.months
        else self.subscription_type == "Annually"
           value_date = value_date + 1.year
       end
    end
    value_date == Date.today
  end


  def subs_month(date)
    notify = false
    value_date = billing_date
    until ((date.beginning_of_month..date.end_of_month) === value_date) || (value_date > date.end_of_month )
       if self.subscription_type == "Monthly"
          value_date = value_date + 1.month
        elsif self.subscription_type == "Quarterly"
           value_date = value_date + 3.months
        elsif self.subscription_type == "Biannually"
           value_date = value_date + 6.months
        else self.subscription_type == "Annually"
           value_date = value_date + 1.year
       end
    end
    p value_date if self.name == "Fitness"
    (date.beginning_of_month..date.end_of_month) === value_date
  end

  def payment_date
    payment_date = billing_date

    until payment_date > Date.today
      if self.subscription_type == "Monthly"
        payment_date = payment_date + 1.month
      elsif self.subscription_type == "Quarterly"
        payment_date = payment_date + 3.months
      elsif self.subscription_type == "Biannually"
        payment_date = payment_date + 6.months
      else self.subscription_type == "Annually"
        payment_date = payment_date + 1.year
      end
    end
    return payment_date
  end

  def category_color
    if self.category == "Media"
      {class_name: 'red', value: 'red'}
    elsif self.category == "Wellbeing"
      {class_name:'green', value: '#5CB566'}
    elsif self.category == "Streaming"
      {class_name:'lightblue', value: 'lightblue'}
    elsif self.category == "Leisure"
      {class_name:'darkblue', value: 'darkblue'}
    elsif self.category == "Social"
      {class_name:'orange', value: 'orange'}
    elsif self.category == "Shopping"
      {class_name:'pink', value: 'pink'}
    elsif self.category == "Food"
      {class_name:'yellow', value: 'yellow'}
    elsif self.category == "Technology"
      {class_name:'gray', value: 'gray'}
    elsif self.category == "Other"
      {class_name:'purple', value: 'purple'}
    end
  end

  def this_month_billing_day
    facture_day = self.billing_date
    i = 0
    if self.subscription_type == "Monthly"
      while facture_day < Date.today.beginning_of_month
        facture_day += i.month
        i += 1
      end
    elsif self.subscription_type == "Quarterly"
      while facture_day < Date.today.beginning_of_month
      facture_day += i.month
      i += 3
      end
    elsif self.subscription_type == "Biannually"
      while facture_day < Date.today.beginning_of_month
      facture_day += i.month
      i += 6
      end
    else self.subscription_type == "Annually"
      while facture_day < Date.today.beginning_of_month
      facture_day += i.month
      i += 12
      end
    end
    return  facture_day
  end

    def previous_billing_day
    facture_day = self.billing_date
    i = 0
    if self.subscription_type == "Monthly"
      while facture_day < Date.today.beginning_of_month
        facture_day += i.month
        i += 1
      end
        facture_day -= 1.month
    elsif self.subscription_type == "Quarterly"
      while facture_day < Date.today.beginning_of_month
      facture_day += i.month
      i += 3
      end
      facture_day -= 3.month
    elsif self.subscription_type == "Biannually"
      while facture_day < Date.today.beginning_of_month
      facture_day += i.month
      i += 6
      end
      facture_day -= 6.month
    else self.subscription_type == "Annually"
      while facture_day < Date.today.beginning_of_month
      facture_day += i.month
      i += 12
      end
      facture_day -= 12.month
    end
    return  facture_day
  end

  def current_billing_day
    facture_day = self.billing_date
    i = 0
    if self.subscription_type == "Monthly"
      while facture_day < Date.today
        facture_day += i.month
        i += 1
      end
    elsif self.subscription_type == "Quarterly"
      while facture_day < Date.today
      facture_day += i.month
      i += 3
      end
    elsif self.subscription_type == "Biannually"
      while facture_day < Date.today
      facture_day += i.month
      i += 6
      end
    else self.subscription_type == "Annually"
      while facture_day < Date.today
      facture_day += i.month
      i += 12
      end
    end
    return  facture_day
  end

  def trial?
    return false if self.trial_date_until.nil?
    self.trial_date_until >= Date.today
  end

  def lifelong_cost2(from_date, to_date)
    price2 = 0
    if self.this_month_billing_day > from_date && self.this_month_billing_day < to_date
      price2 = self.lifelong_cost(from_date, to_date)
    end
    return  price2
  end


end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = current_user.subscriptions.order(created_at: :desc)
  end

  def show  # GET /payment_methods/:id
      @subscription = Subscription.find(params[:id])
      @parasites_to_add = (current_user.parasites - @subscription.parasites).compact
  end

  def new
    @subscription = Subscription.new
  end

  def update
    @subscription = Subscription.find(params[:id])
    if params[:subscription][:parasite_ids]
      params[:subscription][:parasite_ids].reject { |c| c.empty? }.each do |par_id|
         @subscription.parasites << Parasite.find(par_id)
      end
    end
    if @subscription.update(subscription_params)
      redirect_to subscription_path(@subscription), notice: 'Subscription edited'
    else
      render :edit
    end
  end

  def create        # POST /subscribtion
    @subscription = Subscription.new(subscription_params)
    @subscription.user = current_user
    if @subscription.save
      redirect_to subscription_path(@subscription), notice: 'New subscription added'
    else
      render :new
    end
  end

  def edit          # GET /payment_methods/:id/edit
    @subscription = Subscription.find(params[:id])
    @subscription.user = current_user
  end

  # def update
  #   @subscription = Subscription.find(params[:id])
  #   if @subscription.update(subscription_params)
  #     redirect_to subscription_path(@subscription), notice: 'Subscription updated'
  #   else
  #     render :edit
  #   end
  # end

  def add_parasite
    @subscription = Subscription.find(params[:id])
    params[:subscription][:parasite_ids].each do |para|
      @subscription.parasites << Parasite.find(para) unless para.blank?
    end
    @subscription.save
    redirect_to @subscription
  end


  def delete_parasite
    @subscription = Subscription.find(params[:id])
    @parasite = Parasite.find(params[:parasite])
    @relationship_to_destroy = SubscriptionParasite.where(parasite: @parasite).where(subscription:@subscription).first
    @relationship_to_destroy.destroy
    redirect_to subscription_path(@subscription)
  end

  def update_notification
    @subscription = Subscription.find(params[:subscription_id])
    @subscription.renewal_notification = !@subscription.renewal_notification
    @subscription.save
    redirect_to subscriptions_path
  end

  def destroy       # DELETE /payment_methods/:id
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
      # no need for app/views/restaurants/destroy.html.erb
    redirect_to subscriptions_path
  end

  def subscription_params
    params.require(:subscription).permit(:name, :subscription_type, :cost, :category, :creation_date, :renewal_notification, :notification_date, :payment_method_id, :subscription_id, :billing_date, :photo, :trial_date_until, :parasite_ids)
  end
end

app/views/subscriptions/_activesubsc_card.html.erb
<% @subscriptions.each do |subscription| %>
  <div class="card-product">
    <div class="category  <%= subscription.category_color[:class_name] %>" id="wrapper">
      <p class="vertical"><%= subscription.category %></p>
    </div>
    <div class="card-image">
      <%= link_to  subscription_path(subscription) do%>
        <% if subscription.name == "Amazon Prime" %>
          <%= image_tag "amazon.png", alt: "amazon" %>
        <% elsif subscription.name == "Apple Music" %>
          <%= image_tag "apple.png", alt: "apple" %>
        <% elsif subscription.name == "Dropbox" %>
          <%= image_tag "dropbox.png", alt: "dropbox" %>
        <% elsif subscription.name == "iCloud" %>
          <%= image_tag "icloud.png", alt: "icloud" %>
        <% elsif subscription.name == "LinkedIn" %>
          <%= image_tag "linkedin.png", alt: "linkedin" %>
        <% elsif subscription.name == "Netflix" %>
          <%= image_tag "netflix.png", alt: "netflix" %>
        <% elsif subscription.name == "Spotify" %>
          <%= image_tag "spotify.png", alt: "spotify" %>
        <% else %>
          <%= image_tag "logosmall.png", alt: "logo" %>
        <% end %>
      <% end %>
    </div>
    <div class="card-product-infos" id="first">
      <p class="upcase name"><%= subscription.name %></p>
      <p class="price"><%= subscription.cost %> €</p>
      <div class="extra-info">
        <p><%= subscription.this_month_billing_day %> </p>
        <% if subscription.trial? == true %>
        <p class="free-trial"> &nbsp;(Free trial) </p>
        <% else %>
        <p> &nbsp;(<%= subscription.subscription_type%>)</p>
        <% end %>
      </div>
    </div>
    <div class="card-product-infos" id="second">
      <p class="extra-info">payed with <strong>
        <% if subscription.payment_method.nil? %>
           no info
        <% else %>
        <%= subscription.payment_method.card_nickname %>
        <% end %>
        </strong></p>
      <% if subscription.creation_date.nil? %>
        <p class="extra-info"> no creation date </p>
      <% else %>
        <p class="price"> <%= subscription.lifelong_cost(subscription.creation_date, Date.today) %> €</p>
        <p class="extra-info">Total since <%= subscription.creation_date %></p>
      <% end %>
    </div>
    <div class="card-product-infos" id="last">
      <%= simple_form_for subscription, url: subscription_update_notification_path(subscription) do |form| %>
        <% if subscription.renewal_notification == false %>
          <%= form.hidden_field :renewal_notification, value: true %>
          <%= form.button :button, class: "notification" do %>
            <%= image_tag "notification-off.png", alt: "bell", class: "bell", id:"notification-off" %>
          <% end %>
        <% else %>
          <%= form.hidden_field :renewal_notification, value: false %>
          <%= form.button :button, class: "notification" do %>
            <%= image_tag "notification-on.png", alt: "bell", class: "bell", id:"notification-off" %>
          <% end %>
        <% end %>
      <% end %>

      <div class="card-type dropdown">
        <p class="card-type dropdown-toggle subscription-menu" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Options <i class="fas fa-caret-down"></i></p>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Edit", edit_subscription_path(subscription), class: "dropdown-item" %>
          <%= link_to "Remove", subscription_path(subscription), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "dropdown-item" %>
        </div>
      </div>
    </div>
  </div>
<% end %>



<script type="text/javascript">
  var image_tracker = 'off';
  document.getElementById('notification-off').addEventListener('click', ()=> {
    console.log("hello")
    var bell = document.getElementById('notification-off');
    if (image_tracker == 'off'){
      bell.src = '<%= image_path("notification-on.png") %>';
      image_tracker = 'on';
    }else{
      bell.src = '<%= image_path("notification-off.png") %>';
      image_tracker = 'off';
    }
})
</script>

app/views/subscriptions/_form.html.erb
<h3 class="form-title">Create a new Subscription </h3>
<div class="wrapper-form">
  <br>
  <br>
  <div class="container">
    <div class="row">
    <div class = " col-xs-12 col-md-12 offset-12">

  <%= simple_form_for(@subscription) do |f| %>
    <%= f.error_notification %>


      <%= f.input :name, label: 'Name of your service provider/Subscription', input_html: { style: "display: none;"} %>
      <%= f.input :name, placeholder: 'Enter subscription name', label: false, input_html: { id: "nameInput", class: "hidden" } %>
      <%= f.input :name, label: false, collection: ["Amazon Prime", "Apple Music", "Dropbox", "iCloud", "LinkedIn", "Netflix", "Spotify", "Add manually"], select: 'From ', prompt: 'Select your subscription', input_html: { id: "nameDropdown"} %>
      <p> Free trial? </p>
      <p class="notify-me"> <i class="fas fa-info-circle"></i> if this is a Free trial, please enter the ending date of the free trial, if it isn't leave it blank </p>
      <%= f.input  :trial_date_until, label: false, placeholder: "Free trial end date", as: :string, input_html: { class: "datepicker-here" } %>
      <%= f.input :subscription_type, label: 'Billing frequency', collection: ["Monthly", "Quarterly", "Biannually", "Annually"], prompt: 'Select frequency' %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.input :billing_date, placeholder: 'Add your billing date', as: :string, input_html: { class: "datepicker-here", autocomplete: 'off' } %>
      <%= f.input :renewal_notification %>
      <div  id="notif"  class="hidden">
      <%= f.input :notification_date, placeholder: 'Choose date to receive reminder', as: :string, input_html: { class: "datepicker-here" } %>
        </div>

      <%= f.input :cost, label: 'Subscription cost', placeholder: 'Enter your subscription charge', float: 'any' %>
      <%= f.input :creation_date, label: 'Subscription creation date',placeholder: 'Choose subscription start date', as: :string, input_html: { class:  "datepicker-here", autocomplete: 'off' } %>
      <%= f.input :category, placeholder: 'Enter subscription type', collection: ["Media", "Wellbeing", "Streaming", "Leisure", "Social", "Shopping", "Food", "Technology", "Other"] %>
      <%= f.input :payment_method_id, collection: current_user.payment_methods, label_method: :card_nickname %>

    <div class = "form-action form-container">
      <%= f.button :submit, class: 'btn btn-primary form', id: 'back' %>
    </div>

  <% end %>
    </div>

  </div>
  </div>
</div>
<br>
<br>
<br>

app/views/subscriptions/_parasites.html.erb
<div class="parasites-container container">
  <div class="row">
    <% parasites.each do |para| %>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 single-parasite">

        <div class="para-avatar">
          <p class="initial"><%=  para.name[0,1] %></p>
        </div>
        <div class="para-details">
          <p class="para-name"><%=  para.name %></p>
          <%= link_to delete_parasite_subscription_path(parasite: para), method: :delete, data: { confirm: "Are your friend isn't using this service anymore?" }  do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/subscriptions/edit.html.erb
<%= render 'subscriptions/form', subscriptions: @subscriptions %>

app/views/subscriptions/index.html.erb
<!-- <div class="tab">
  <button class="tablinks" onclick="openSubscription(event, 'Active subscriptions')">Active subscriptions</button>
  <button class="tablinks" onclick="openSubscription(event, 'Inactive subscriptions')">Inactive subscriptions</button>
</div> -->

<!-- Tab content
<div id="Active" class="tabcontent">
  <h3>Active subscriptions</h3>
  <p>all cards go here now</p>
</div>

<div id="Paris" class="tabcontent">
  <h3>Inactive subscriptions</h3>
  <p>cards of history of subscriptions</p>
</div>

 -->

    <%= render "activesubsc_card" %>

  <br>
<div class="button-wrapper">
  <div id="back" class="btn btn-primary index">
    <%= link_to "Add a subscription", new_subscription_path   %>
  </div>
  <br>
  <br>
</div>

app/views/subscriptions/new.html.erb
 <%= render 'subscriptions/form', subscriptions: @subscriptions %>

app/views/subscriptions/show.html.erb
<div class="container">
  <div class="main-container-show">
    <div class="card-image-show" class="btn btn-primary">

        <% if @subscription.name == "Amazon Prime" %>
          <%= image_tag "amazon.png", alt: "amazon" %>
        <% elsif @subscription.name == "Apple Music" %>
          <%= image_tag "apple.png", alt: "apple" %>
        <% elsif @subscription.name == "Dropbox" %>
          <%= image_tag "dropbox.png", alt: "dropbox" %>
        <% elsif @subscription.name == "iCloud" %>
          <%= image_tag "icloud.png", alt: "icloud" %>
        <% elsif @subscription.name == "LinkedIn" %>
          <%= image_tag "linkedin.png", alt: "linkedin" %>
        <% elsif @subscription.name == "Netflix" %>
          <%= image_tag "netflix.png", alt: "netflix" %>
        <% elsif @subscription.name == "Spotify" %>
          <%= image_tag "spotify.png", alt: "spotify" %>
        <% else %>
          <%= image_tag "logosmall.png", alt: "logo" %>
        <% end %>
    </div>

    <div class="field zero">
      <% if @subscription.trial? == true %>
      <h4 style="color:red; font-weight: bold"> This is a Free Trial until <%= @subscription.trial_date_until %></h4>
      <% end %>
    </div>
    <div class="square">
      <h4 class="cost"><%= @subscription.cost %> EUR</h4>
      <p>(<%= @subscription.subscription_type %>)</p>
    </div>
    <div class="field first">
      <h4>Billing date</h4>
      <p><%= @subscription.billing_date %></p>
    </div>
    <div class="field second">
      <h4>Subscription started</h4>
      <% if @subscription.creation_date.present? %>
        <p><%= @subscription.creation_date %></p>
       <% else %>
        <p> Incomplete data set </p>
        <% end %>
    </div>
    <div class="field third">
      <h4>Total expenditure </h4>
      <% if @subscription.creation_date.present? %>
        <p><%= @subscription.lifelong_cost(Date.today - 10.years, Date.today) %></p>
       <% else %>
       <p> Incomplete data set </p>
      <% end %>
    </div>
    <div class="field forth">
      <h4>Category</h4>
      <p><%= @subscription.category %></p>
    </div>
    <div class="field fith">
      <h4>Card </h4>
      <% if @subscription.payment_method.present? %>
      <p><%= @subscription.payment_method.card_nickname %></p>
      <% else %>
      <p> no info </p>
      <% end %>
    </div>
    <div class="field sixth">
      <% if @subscription.renewal_notification == true %>
        <h4> Notifications: ON </h4>
        <p> Notification Date: <%= @subscription.notification_date %></p>
      <% else %>
        <h4> Notifications: OFF </h4>
      <% end %>
      </ul>
    </div>
    <div class="field seventh">
      <h4> Current Account Users </h4>
      <div class="Parasites-my-profile">
        <%= render "parasites", parasites: @subscription.parasites %>
      </div>

      <div class="add-friend">
        <%= simple_form_for @subscription, url: subscription_path(@subscription) do |f| %>
        <%= f.association :parasites, collection: @parasites_to_add, label: "Add user to subscription"  %>
        <div class="add-btn-container">
        <%= f.submit :Add, id: "back", class: "text-center btn btn-primary" %>
        </div>
        <% end %>
      </div >
    </div>
  </div>
</div>